// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.StudentFormComponentTests")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:Tnosc.OtripleS.Client.Web.Tests.Unit.StudentFormComponentTests.renderedStudentFormComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.Register.StudentServiceTests")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionAddIfBadRequestErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionOnAddIfConflictErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionOnRegisterIfConflictErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionRegisterIfBadRequestErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.CriticalApiException~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnAddIfCriticalErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnRegisterIfCriticalErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnRegisterIfCriticalErrorOccursAndLogItAsync(System.Exception)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.DependencyApiException~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyExceptionOnRegisterIfCriticalErrorOccursAndLogItAsync(System.Exception)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowServiceExceptionOnAddIfErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowServiceExceptionOnAddIfErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.StudentServiceValidationExceptions~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyValidationExceptionOnAddIfStudentValidationErrorOccuredAndLogItAsync(System.Exception)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyValidationExceptionOnRegisterIfStudentValidationErrorOccurredAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyValidationExceptionOnRegisterIfDependencyValidationErrorOccurredAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.DependencyExceptions~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyExceptionOnUpsertIfDependencyErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyExceptionOnRegisterIfDependencyErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowDependencyValidationExceptionOnRegisterIfDependencyValidationErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowServiceExceptionOnRegisterIfServiceErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Views.Students.StudentViewServiceTests.ShouldThrowServiceExceptionOnRegisterIfServiceErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests._renderedStudentRegistrationComponent")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests.StudentViewValidationExceptions~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests.ShouldRenderInnerExceptionMessageIfValidationErrorOccurred(Xeptions.Xeption)")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests.ShouldRenderExceptionMessageIfDependencyOrServiceErrorOccurred(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2012:Use ValueTasks correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Components.Students.StudentRegistrationComponentTests.ShouldDisplaySubmittingStatusAndDisabledControlsBeforeStudentSubmissionCompletes~System.Threading.Tasks.Task")]
