// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.StudentFormComponentTests")]
[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:Tnosc.OtripleS.Client.Web.Tests.Unit.StudentFormComponentTests.renderedStudentFormComponent")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.Register.StudentServiceTests")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionAddIfBadRequestErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionOnAddIfConflictErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionOnRegisterIfConflictErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowDependencyValidationExceptionRegisterIfBadRequestErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.CriticalApiException~Xunit.TheoryData")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnAddIfCriticalErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnRegisterIfCriticalErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Client.Web.Tests.Unit.Services.Foundations.StudentServiceTests.ShouldThrowCriticalDependencyExceptionOnRegisterIfCriticalErrorOccursAndLogItAsync(System.Exception)~System.Threading.Tasks.Task")]
